/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DsAuthResp
 */
export interface DsAuthResp {
    /**
     * 
     * @type {string}
     * @memberof DsAuthResp
     */
    token?: string;
}

/**
 * Check if a given object implements the DsAuthResp interface.
 */
export function instanceOfDsAuthResp(value: object): value is DsAuthResp {
    return true;
}

export function DsAuthRespFromJSON(json: any): DsAuthResp {
    return DsAuthRespFromJSONTyped(json, false);
}

export function DsAuthRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsAuthResp {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function DsAuthRespToJSON(json: any): DsAuthResp {
    return DsAuthRespToJSONTyped(json, false);
}

export function DsAuthRespToJSONTyped(value?: DsAuthResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

