/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DsErrorResp
 */
export interface DsErrorResp {
    /**
     * 
     * @type {string}
     * @memberof DsErrorResp
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DsErrorResp
     */
    status?: string;
}

/**
 * Check if a given object implements the DsErrorResp interface.
 */
export function instanceOfDsErrorResp(value: object): value is DsErrorResp {
    return true;
}

export function DsErrorRespFromJSON(json: any): DsErrorResp {
    return DsErrorRespFromJSONTyped(json, false);
}

export function DsErrorRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsErrorResp {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function DsErrorRespToJSON(json: any): DsErrorResp {
    return DsErrorRespToJSONTyped(json, false);
}

export function DsErrorRespToJSONTyped(value?: DsErrorResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'status': value['status'],
    };
}

