/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DsChatResponse } from './DsChatResponse';
import {
    DsChatResponseFromJSON,
    DsChatResponseFromJSONTyped,
    DsChatResponseToJSON,
    DsChatResponseToJSONTyped,
} from './DsChatResponse';

/**
 * 
 * @export
 * @interface DsGetChatsResponse
 */
export interface DsGetChatsResponse {
    /**
     * 
     * @type {Array<DsChatResponse>}
     * @memberof DsGetChatsResponse
     */
    chats?: Array<DsChatResponse>;
    /**
     * 
     * @type {number}
     * @memberof DsGetChatsResponse
     */
    draftID?: number;
    /**
     * 
     * @type {number}
     * @memberof DsGetChatsResponse
     */
    draftCount?: number;
}

/**
 * Check if a given object implements the DsGetChatsResponse interface.
 */
export function instanceOfDsGetChatsResponse(value: object): value is DsGetChatsResponse {
    return true;
}

export function DsGetChatsResponseFromJSON(json: any): DsGetChatsResponse {
    return DsGetChatsResponseFromJSONTyped(json, false);
}

export function DsGetChatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsGetChatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'chats': json['chats'] == null ? undefined : ((json['chats'] as Array<any>).map(DsChatResponseFromJSON)),
        'draftID': json['draft_ID'] == null ? undefined : json['draft_ID'],
        'draftCount': json['draft_count'] == null ? undefined : json['draft_count'],
    };
}

export function DsGetChatsResponseToJSON(json: any): DsGetChatsResponse {
    return DsGetChatsResponseToJSONTyped(json, false);
}

export function DsGetChatsResponseToJSONTyped(value?: DsGetChatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chats': value['chats'] == null ? undefined : ((value['chats'] as Array<any>).map(DsChatResponseToJSON)),
        'draft_ID': value['draftID'],
        'draft_count': value['draftCount'],
    };
}

