/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DsMessageResp
 */
export interface DsMessageResp {
    /**
     * 
     * @type {number}
     * @memberof DsMessageResp
     */
    creatorId?: number;
    /**
     * 
     * @type {string}
     * @memberof DsMessageResp
     */
    dateCreate?: string;
    /**
     * 
     * @type {string}
     * @memberof DsMessageResp
     */
    dateFinish?: string;
    /**
     * 
     * @type {string}
     * @memberof DsMessageResp
     */
    dateUpdate?: string;
    /**
     * 
     * @type {number}
     * @memberof DsMessageResp
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof DsMessageResp
     */
    moderatorId?: number;
    /**
     * 
     * @type {string}
     * @memberof DsMessageResp
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof DsMessageResp
     */
    text?: string;
}

/**
 * Check if a given object implements the DsMessageResp interface.
 */
export function instanceOfDsMessageResp(value: object): value is DsMessageResp {
    return true;
}

export function DsMessageRespFromJSON(json: any): DsMessageResp {
    return DsMessageRespFromJSONTyped(json, false);
}

export function DsMessageRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsMessageResp {
    if (json == null) {
        return json;
    }
    return {
        
        'creatorId': json['creator_id'] == null ? undefined : json['creator_id'],
        'dateCreate': json['date_create'] == null ? undefined : json['date_create'],
        'dateFinish': json['date_finish'] == null ? undefined : json['date_finish'],
        'dateUpdate': json['date_update'] == null ? undefined : json['date_update'],
        'id': json['id'] == null ? undefined : json['id'],
        'moderatorId': json['moderator_id'] == null ? undefined : json['moderator_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function DsMessageRespToJSON(json: any): DsMessageResp {
    return DsMessageRespToJSONTyped(json, false);
}

export function DsMessageRespToJSONTyped(value?: DsMessageResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creator_id': value['creatorId'],
        'date_create': value['dateCreate'],
        'date_finish': value['dateFinish'],
        'date_update': value['dateUpdate'],
        'id': value['id'],
        'moderator_id': value['moderatorId'],
        'status': value['status'],
        'text': value['text'],
    };
}

