/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DsChatResponseWithFlags } from './DsChatResponseWithFlags';
import {
    DsChatResponseWithFlagsFromJSON,
    DsChatResponseWithFlagsFromJSONTyped,
    DsChatResponseWithFlagsToJSON,
    DsChatResponseWithFlagsToJSONTyped,
} from './DsChatResponseWithFlags';

/**
 * 
 * @export
 * @interface DsMessageDetail
 */
export interface DsMessageDetail {
    /**
     * 
     * @type {Array<DsChatResponseWithFlags>}
     * @memberof DsMessageDetail
     */
    chats?: Array<DsChatResponseWithFlags>;
    /**
     * 
     * @type {string}
     * @memberof DsMessageDetail
     */
    creator?: string;
    /**
     * 
     * @type {string}
     * @memberof DsMessageDetail
     */
    dateCreate?: string;
    /**
     * 
     * @type {string}
     * @memberof DsMessageDetail
     */
    dateFinish?: string;
    /**
     * 
     * @type {string}
     * @memberof DsMessageDetail
     */
    dateUpdate?: string;
    /**
     * 
     * @type {number}
     * @memberof DsMessageDetail
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DsMessageDetail
     */
    moderator?: string;
    /**
     * 
     * @type {string}
     * @memberof DsMessageDetail
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof DsMessageDetail
     */
    text?: string;
}

/**
 * Check if a given object implements the DsMessageDetail interface.
 */
export function instanceOfDsMessageDetail(value: object): value is DsMessageDetail {
    return true;
}

export function DsMessageDetailFromJSON(json: any): DsMessageDetail {
    return DsMessageDetailFromJSONTyped(json, false);
}

export function DsMessageDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsMessageDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'chats': json['chats'] == null ? undefined : ((json['chats'] as Array<any>).map(DsChatResponseWithFlagsFromJSON)),
        'creator': json['creator'] == null ? undefined : json['creator'],
        'dateCreate': json['date_create'] == null ? undefined : json['date_create'],
        'dateFinish': json['date_finish'] == null ? undefined : json['date_finish'],
        'dateUpdate': json['date_update'] == null ? undefined : json['date_update'],
        'id': json['id'] == null ? undefined : json['id'],
        'moderator': json['moderator'] == null ? undefined : json['moderator'],
        'status': json['status'] == null ? undefined : json['status'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function DsMessageDetailToJSON(json: any): DsMessageDetail {
    return DsMessageDetailToJSONTyped(json, false);
}

export function DsMessageDetailToJSONTyped(value?: DsMessageDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chats': value['chats'] == null ? undefined : ((value['chats'] as Array<any>).map(DsChatResponseWithFlagsToJSON)),
        'creator': value['creator'],
        'date_create': value['dateCreate'],
        'date_finish': value['dateFinish'],
        'date_update': value['dateUpdate'],
        'id': value['id'],
        'moderator': value['moderator'],
        'status': value['status'],
        'text': value['text'],
    };
}

