/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DsOkResp
 */
export interface DsOkResp {
    /**
     * 
     * @type {string}
     * @memberof DsOkResp
     */
    message?: string;
}

/**
 * Check if a given object implements the DsOkResp interface.
 */
export function instanceOfDsOkResp(value: object): value is DsOkResp {
    return true;
}

export function DsOkRespFromJSON(json: any): DsOkResp {
    return DsOkRespFromJSONTyped(json, false);
}

export function DsOkRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsOkResp {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function DsOkRespToJSON(json: any): DsOkResp {
    return DsOkRespToJSONTyped(json, false);
}

export function DsOkRespToJSONTyped(value?: DsOkResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

