/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DsUpdateMessageTextInput
 */
export interface DsUpdateMessageTextInput {
    /**
     * Обязательное поле текста
     * @type {string}
     * @memberof DsUpdateMessageTextInput
     */
    text: string;
}

/**
 * Check if a given object implements the DsUpdateMessageTextInput interface.
 */
export function instanceOfDsUpdateMessageTextInput(value: object): value is DsUpdateMessageTextInput {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function DsUpdateMessageTextInputFromJSON(json: any): DsUpdateMessageTextInput {
    return DsUpdateMessageTextInputFromJSONTyped(json, false);
}

export function DsUpdateMessageTextInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsUpdateMessageTextInput {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function DsUpdateMessageTextInputToJSON(json: any): DsUpdateMessageTextInput {
    return DsUpdateMessageTextInputToJSONTyped(json, false);
}

export function DsUpdateMessageTextInputToJSONTyped(value?: DsUpdateMessageTextInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

