/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DsUpdateMessageTextResp
 */
export interface DsUpdateMessageTextResp {
    /**
     * 
     * @type {string}
     * @memberof DsUpdateMessageTextResp
     */
    text?: string;
}

/**
 * Check if a given object implements the DsUpdateMessageTextResp interface.
 */
export function instanceOfDsUpdateMessageTextResp(value: object): value is DsUpdateMessageTextResp {
    return true;
}

export function DsUpdateMessageTextRespFromJSON(json: any): DsUpdateMessageTextResp {
    return DsUpdateMessageTextRespFromJSONTyped(json, false);
}

export function DsUpdateMessageTextRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsUpdateMessageTextResp {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function DsUpdateMessageTextRespToJSON(json: any): DsUpdateMessageTextResp {
    return DsUpdateMessageTextRespToJSONTyped(json, false);
}

export function DsUpdateMessageTextRespToJSONTyped(value?: DsUpdateMessageTextResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

