/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DsUserRegisterResp
 */
export interface DsUserRegisterResp {
    /**
     * 
     * @type {number}
     * @memberof DsUserRegisterResp
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DsUserRegisterResp
     */
    isModerator?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DsUserRegisterResp
     */
    login?: string;
}

/**
 * Check if a given object implements the DsUserRegisterResp interface.
 */
export function instanceOfDsUserRegisterResp(value: object): value is DsUserRegisterResp {
    return true;
}

export function DsUserRegisterRespFromJSON(json: any): DsUserRegisterResp {
    return DsUserRegisterRespFromJSONTyped(json, false);
}

export function DsUserRegisterRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsUserRegisterResp {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'isModerator': json['is_moderator'] == null ? undefined : json['is_moderator'],
        'login': json['login'] == null ? undefined : json['login'],
    };
}

export function DsUserRegisterRespToJSON(json: any): DsUserRegisterResp {
    return DsUserRegisterRespToJSONTyped(json, false);
}

export function DsUserRegisterRespToJSONTyped(value?: DsUserRegisterResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'is_moderator': value['isModerator'],
        'login': value['login'],
    };
}

