/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DsUserUpdateReq
 */
export interface DsUserUpdateReq {
    /**
     * 
     * @type {string}
     * @memberof DsUserUpdateReq
     */
    currentPassword?: string;
    /**
     * 
     * @type {string}
     * @memberof DsUserUpdateReq
     */
    newPassword?: string;
}

/**
 * Check if a given object implements the DsUserUpdateReq interface.
 */
export function instanceOfDsUserUpdateReq(value: object): value is DsUserUpdateReq {
    return true;
}

export function DsUserUpdateReqFromJSON(json: any): DsUserUpdateReq {
    return DsUserUpdateReqFromJSONTyped(json, false);
}

export function DsUserUpdateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsUserUpdateReq {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['current_password'] == null ? undefined : json['current_password'],
        'newPassword': json['new_password'] == null ? undefined : json['new_password'],
    };
}

export function DsUserUpdateReqToJSON(json: any): DsUserUpdateReq {
    return DsUserUpdateReqToJSONTyped(json, false);
}

export function DsUserUpdateReqToJSONTyped(value?: DsUserUpdateReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_password': value['currentPassword'],
        'new_password': value['newPassword'],
    };
}

