/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DsUserRegisterReq
 */
export interface DsUserRegisterReq {
    /**
     * 
     * @type {string}
     * @memberof DsUserRegisterReq
     */
    login?: string;
    /**
     * 
     * @type {string}
     * @memberof DsUserRegisterReq
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof DsUserRegisterReq
     */
    repeatPassword?: string;
}

/**
 * Check if a given object implements the DsUserRegisterReq interface.
 */
export function instanceOfDsUserRegisterReq(value: object): value is DsUserRegisterReq {
    return true;
}

export function DsUserRegisterReqFromJSON(json: any): DsUserRegisterReq {
    return DsUserRegisterReqFromJSONTyped(json, false);
}

export function DsUserRegisterReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsUserRegisterReq {
    if (json == null) {
        return json;
    }
    return {
        
        'login': json['login'] == null ? undefined : json['login'],
        'password': json['password'] == null ? undefined : json['password'],
        'repeatPassword': json['repeat_password'] == null ? undefined : json['repeat_password'],
    };
}

export function DsUserRegisterReqToJSON(json: any): DsUserRegisterReq {
    return DsUserRegisterReqToJSONTyped(json, false);
}

export function DsUserRegisterReqToJSONTyped(value?: DsUserRegisterReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'login': value['login'],
        'password': value['password'],
        'repeat_password': value['repeatPassword'],
    };
}

