/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DsUser
 */
export interface DsUser {
    /**
     * 
     * @type {number}
     * @memberof DsUser
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DsUser
     */
    isModerator?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DsUser
     */
    login?: string;
    /**
     * 
     * @type {string}
     * @memberof DsUser
     */
    password?: string;
}

/**
 * Check if a given object implements the DsUser interface.
 */
export function instanceOfDsUser(value: object): value is DsUser {
    return true;
}

export function DsUserFromJSON(json: any): DsUser {
    return DsUserFromJSONTyped(json, false);
}

export function DsUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'isModerator': json['is_moderator'] == null ? undefined : json['is_moderator'],
        'login': json['login'] == null ? undefined : json['login'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function DsUserToJSON(json: any): DsUser {
    return DsUserToJSONTyped(json, false);
}

export function DsUserToJSONTyped(value?: DsUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'is_moderator': value['isModerator'],
        'login': value['login'],
        'password': value['password'],
    };
}

