/* tslint:disable */
/* eslint-disable */
/**
 * Mailing app
 * my api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DsUserRespReq
 */
export interface DsUserRespReq {
    /**
     * 
     * @type {string}
     * @memberof DsUserRespReq
     */
    login?: string;
    /**
     * 
     * @type {string}
     * @memberof DsUserRespReq
     */
    password?: string;
}

/**
 * Check if a given object implements the DsUserRespReq interface.
 */
export function instanceOfDsUserRespReq(value: object): value is DsUserRespReq {
    return true;
}

export function DsUserRespReqFromJSON(json: any): DsUserRespReq {
    return DsUserRespReqFromJSONTyped(json, false);
}

export function DsUserRespReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): DsUserRespReq {
    if (json == null) {
        return json;
    }
    return {
        
        'login': json['login'] == null ? undefined : json['login'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function DsUserRespReqToJSON(json: any): DsUserRespReq {
    return DsUserRespReqToJSONTyped(json, false);
}

export function DsUserRespReqToJSONTyped(value?: DsUserRespReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'login': value['login'],
        'password': value['password'],
    };
}

